"""create tables

Revision ID: 47628a93ac19
Revises: 9853444c0a9f
Create Date: 2023-09-09 17:55:04.852714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47628a93ac19'
down_revision = '9853444c0a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_department_departments'), 'departments', ['department'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_department_departments'), type_='foreignkey')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
